### ISSUE TITLE
Resolve 'Path variable "APP_VERSION" is not consumed' controller warning

### ISSUE THREAD

**Issue by NichiforeacNicolae** [Nowire-Space/learnromanian-rest#12]
**Description:**
'Path variable 'APP_VERSION' is not consumed' warn is thrown on every method at controller level.
Should be investigated and fixed.
Possible problem could be ENV used on server.servlet.context-path setting inside application.yml
![Image](https://github.com/Nowire-Space/learnromanian-rest/assets/57327282/28b81a02-e800-4fef-a2c2-605c82a14e3c)

**Acceptance criteria:**
- [x] Problem causing warn is found
- [ ] Warn is fixed

**Comment by bogdanDab76** [comment]
The problem came from application.yml:   
servlet:
    context-path: /learnromanian/v${APP_VERSION}/api
The relative path started with String literal combined with env-variable and this will generate the warn. If will start the relative path with the env_variable, the warn doesn't appear even will contain String literal subpath.

**Comment by bogdanDab76** [comment]
Fixed : context-path: /learnromanian/${APP_VERSION}/api
Changed in the env variable : APP_VERSION=v0.0.1
