### ISSUE TITLE
Organize API validators errors

### ISSUE THREAD

**Issue by NichiforeacNicolae** [Nowire-Space/learnromanian-rest#13]
**Description:**
All checks from service layer should be added to validators and response messages should be updated.

**Acceptance criteria:**
- [x] Checks from service layer are added to new validators
- [x] Response messages should be created and organised

**Comment by bogdanDab76** [comment]
Created validators for create and authenticate account. Issue with creation of validator for account validation because the method "validate ()" from AccountService is not calling the validation method because of @PathVariable on parameter.

**Comment by bogdanDab76** [comment]
Response messages created in case of invalid data for RegistrationRequest, LoginRequest and PasswordRegistrationRequest fields marked with validators like @Size.
Response messages are generates in case of error codes by ExceptionHandler class adnotated with @ControllerAdvice.
