### ISSUE TITLE
Spring method security implementation

### ISSUE THREAD

**Issue by NichiforeacNicolae** [Nowire-Space/learnromanian-rest#14]
**Description:**
Spring Security configuration should be implemented using method security

**Acceptance criteria:**
- [x] Migrate Spring Security configuration to method security
- [x] Update/add Spring Security tests

**Comment by bogdanDab76** [comment]
Implemented the security methodes with the roles described bellow:
Roles
Create (ALL) -> Validate (ALL) -> Enable (ADMIN) -> Authentication (ALL).
resetPassword (ALL), generateNewPassword (ALL)
getUserProfile(MODERATOR, PROFESOR), getAll(MODERATOR, PROFESSOR)

Created the tests for the authorisation methods.
